Add support for Public Clients and add PKCE
IFCA/keystoneauth-oidc pull request #4
Opened 2020-10-14 19:56 UTC by dannymeloy

Addition of [Proof Key for Exchange (PKCE)](https://tools.ietf.org/html/rfc7636) support for public clients.

These changes allow for the omission of the `--os-client-secret` parameter for public clients who do not have a full set of client credentials. This allows for the common use case of people accessing openstack from command line clients that act as "public clients" which should not have client secrets as per the [OAuth Spec](https://tools.ietf.org/html/rfc6749#page-14).

PKCE is thus added to counter auth code highjacking and replay attacks as recommended in the [OAuth Best Practice Guide](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-16.html#section-2.1.1).

2020-10-19 09:44 UTC, alvarolopez requested changes
Hello @dannymeloy, many thanks for your change!

Could you please adjust one extra minor thing? I would be glad to merge it one that this is done.

Best.

2020-10-19 09:44 UTC, alvarolopez commented on keystoneauth_oidc/plugin.py
> +import pkce
Please, use alphabetic-order for imports

2020-10-20 18:09 UTC, dannymeloy commented
Thanks @alvarolopez for taking a look at it. I've made the requested changes.

2020-11-19 08:44 UTC, alvarolopez approved these changes

2020-11-26 12:35 UTC, dannymeloy commented
Hi @alvarolopez - could this PR be merged into master?

2020-12-04 09:33 UTC, alvarolopez commented
@dannymeloy sure, sorry I overlooked this.

2020-12-04 09:33 UTC, merged

2020-12-04 09:33 UTC, alvarolopez commented
Many thanks for contributing it!